dotfiles_dir = "dotfiles"

[settings.dots]
fish = { source = "fish", target = ".config/fish" }
helix = { source = "helix", target = ".config/helix" }
zellij = { source = "zellij", target = ".config/zellij" }
npm = { source = "npmrc", target = ".npmrc" }
gitconfig = { source = "gitconfig", target = ".gitconfig" }
sway = { source = "sway", target = ".config/sway" }
waybar = { source = "waybar", target = ".config/waybar" }
kitty = { source = "kitty.conf", target = ".config/kitty/kitty.conf" }
mako = { source = "mako", target = ".config/mako" }
kanshi = { source = "kanshi", target = ".config/kanshi" }
cargo = { source = "cargo", target = ".config/cargo" }
nvmrc = { source = "nvmrc", target = ".nvmrc" }
